title: "AJ ONeal"
theme: "eon"
baseURL: "https://coolaj86.github.io/digitalcash.dev"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "AJ ONeal"
  email: "aj@therootcompany.com"
copyright: "© AJ ONeal"
languageCode: "en-us"

Params:
  gravatar: true
  show_edit: "Suggest Edit"
  git_repo: "https://github.com/coolaj86/digitalcash.dev"
  git_branch: "main"
  git_host: "github"
  utterences_repo: "coolaj86/digitalcash.dev"
  utterences_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
