title: "DigitalCash.dev"
theme: "eon"
baseURL: "https://digitalcash.dev"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "AJ ONeal"
  email: "aj@therootcompany.com"
languageCode: "en-us"

Params:
  copyright: "© Dash Developers"
  gravatar: true
  show_edit: "Suggest Edit"
  show_source: "Git Source"
  suggest_edit: "Suggest Edit"
  git_repo: "https://github.com/digitalcashdev/digitalcash.dev"
  git_branch: "main"
  git_host: "github"
  utterances_repo: "digitalcashdev/digitalcash.dev"
  utterances_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
